spring:
  application:
    name: hot-deal-mcp

  ai:
    mcp:
      server:
        protocol: STREAMABLE

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=100,expireAfterWrite=5m

server:
  port: ${PORT:8080}

app:
  public-base-url: ${PUBLIC_BASE_URL:https://a77b-110-12-100-12.ngrok-free.app}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.joeylee.hot_deal_mcp: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
